export const MQTT_CONNECT = "MQTT_CONNECT";
export const MQTT_CONNECTED = "MQTT_CONNECTED";
export const MQTT_DISCONNECT = "MQTT_DISCONNECT";
export const MQTT_DISCONNECTED = "MQTT_DISCONNECTED";
export const MQTT_ONMESSAGE = "MQTT_ONMESSAGE";
